### PR TITLE
Update script to pick appropriate php installation

### PR DESCRIPTION
**Pull request by Plytas**
Script taken from https://github.com/tillkruss/alfred-laravel-docs/pull/22
Solves #8

### CODE REVIEW

**Comment by kennyhorna** [comment]
@Plytas Nice! 
How can I build it locally? To use it until the PR is approved

**Comment by Plytas** [comment]
@kennyhorna you can open the workflow in tableplus, doubleclick the first script filter and replace the script with 
```BASH
if [ -f "/opt/homebrew/bin/php" ]; then
    /opt/homebrew/bin/php tableplus.php "$1"
elif [ -f "/usr/local/bin/php" ]; then
    /usr/local/bin/php tableplus.php "$1"
elif [ -f "/usr/bin/php" ]; then
    /usr/bin/php tableplus.php "$1"
fi
```

Should look like 
image

**Comment by Plytas** [comment]
@chrisrenga Sorry for the ping. Would it be possible to merge it?

**Comment by kennyhorna** [comment]
Thanks for the fast reply @Plytas

**Comment by chrisrenga** [comment]
@Plytas thanks for this.

**Pull request merged**
